version: "2"

services:
  voting-app:
    image: nig-vote
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    image: nig-result
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: worker
    depends_on:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: